obstacle_range: 3.0
raytrace_range: 4.0
footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
#robot_radius: ir_of_robot
inflation_radius: 0.325
# transform_tolerance: 0.2
# cost_scaling_factor: 10.0 

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {
  sensor_frame: laser_filt, 
  data_type:    LaserScan, 
  topic:        /scan_filtered,
  marking:      true, 
  clearing:     true
}

point_cloud_sensor: {
  sensor_frame: frame_name,
  data_type: PointCloud2,
  topic: /kinect2/sd/points,
  marking: true,
  clearing: true
}
