base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS
# base_global_planner: global_planner/GlobalPlanner
# base_local_planner: dwa_local_planner/DWAPlannerROS

controller_frequency: 5.5
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true
clearing_radius: 0.55
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
planner_frequency: 3.0


NavfnROS:
  allow_unknown: true
  planner_window_x: 0.0
  planner_window_y: 0.0
  default_tolerance: 0.5
  visualize_potential: false
  
TrajectoryPlannerROS:
  acc_lim_x: 3.0
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  max_vel_x: 2.0
  min_vel_x: 0.1
  max_vel_theta: 3.0
  min_vel_theta: -3.0
  min_in_place_vel_theta: 0.4
  holonomic_robot: false
  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 5
  vtheta_samples: 20
  controller_frequency: 5.5
  meter_scoring: true
  dwa: true
  prune_plan: true
  
#GlobalPlanner:
#  allow_unknown: true
#  default_tolerance: 0.5
#  use_dijkstra: false
#  use_quadratic: true
#  old_navfn_behavior: false
# 
#DWAPlannerROS:
#  acc_lim_x: 3.0
#  acc_lim_y: 0.0 
#  acc_lim_theta: 3.2
#  max_trans_vel: 2.0
#  min_trans_vel: 0.1
#  max_vel_x: 2.0
#  min_vel_x: 0.1
#  max_vel_y: 0.0
#  min_vel_y: 0.0
#  max_rot_vel: 3.0
#  min_rot_vel: 0.4
#  # Forward Simulation Parameters
#  sim_time: 2.0
#  sim_granularity: 0.025
#  vx_samples: 5
#  vy_samples: 0
#  vtheta_samples: 20
#  controller_frequency: 6.0



